In [1]:
!pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: matplotlib in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (3.10.1)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\satak\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\satak\appdata\roaming\python\python312\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\satak\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.2.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\satak\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ------------------- -------------------- 3.9/8.0 MB 19.5 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 19.4 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 18.4 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   --- ------------------------------------ 2.9/36.5 MB 13.9 MB/s eta 0:00:03
   ------ --------------------------------- 5.5/36.5 MB 13.4 MB/s eta 0:00:03
   --------- ------------------------------ 8.7/36.5 MB 13.4 MB/s eta 0:00:03
   ------------ --------------------------- 11.5/36.5 MB 13.9 MB/s eta 0:00:02
   --------------- ------------------------ 14.4/36.5 MB 13.7 MB/s eta 0:00:02
   ------------------ --------------------- 17.3/36.5 MB 13.6 MB/s eta 0:00:02
   --------------------- ------------------ 19.7/36.5 MB 13.4 MB/s eta 0:00:02
   ----------------------- ---------------- 21.5/36.5 MB 12.8 MB/s eta 0:00:02
   ------------------------- -------------- 23.3/36.5 MB 12.4 MB/s eta 0:00:02
   ---------------------------- ----------- 25.7/36.5 MB 12.1 MB/s eta 0:00:01
   ------------------------------ --------- 27.8/36.5 MB 12.1 MB/s eta 0:00:01
   -------------------------------- ------- 30.1/36.5 MB 11.9 MB/s eta 0:00:01
   ----------------------------------- ---- 32.5/36.5 MB 11.9 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.5 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 11.4 MB/s  0:00:03
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn, seaborn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   -------------------------------- ------- 4/5 [seaborn]
   -------------------------------- ------- 4/5 [seaborn]
   -------------------------------- ------- 4/5 [seaborn]
   -------------------------------- ------- 4/5 [seaborn]
   -------------------------------- ------- 4/5 [seaborn]
   ---------------------------------------- 5/5 [seaborn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 seaborn-0.13.2 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import pandas as pd

trades = pd.read_csv("data/historical_data.csv")
sentiment = pd.read_csv("data/fear_greed_index.csv")

trades.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [5]:
sentiment.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [ ]:
|